### ISSUE TITLE
use Literal notation for set instead of set() in test_seq_traverse

### ISSUE THREAD

**Issue by AbhinavOmprakash** [AbhinavOmprakash/functionali#2]
It's a simple thing just replace `set()` with `{}`

For example

```Python
set([1,2,3]) == {1,2,3}
```

**Comment by svenkat19** [comment]
I would like to work on this

**Comment by AbhinavOmprakash** [comment]
go ahead, I'm glad to have a contributor :)

**Comment by AbhinavOmprakash** [comment]
I've just pushed a commit, it has changes to the file you're working on, just pull that.
