### ISSUE TITLE
Add examples to the docstring of concat

### ISSUE THREAD

**Issue by AbhinavOmprakash** [AbhinavOmprakash/functionali#7]
https://github.com/AbhinavOmprakash/functionali/blob/e22abd7c77ddb89a03a5e1c7e26d2a79fa4964e6/functionali/seq_transform.py#L86-L87

You can refer to the tests for conj and concat
https://github.com/AbhinavOmprakash/functionali/blob/e22abd7c77ddb89a03a5e1c7e26d2a79fa4964e6/tests/test_seq_transform.py#L24-L41

**Comment by kadatatlukishore** [comment]
Is it just same as `conj()` only?

**Comment by AbhinavOmprakash** [comment]
`concat()` and `conj()` have the same behavior for all data structures other than deque.

just include an example Of a list and a deque.

**Comment by kadatatlukishore** [comment]
``` bash
>>> concat([1,2,3,4],5)
    [1, 2, 3, 4, 5]
>>> concat(deque([1,2]), 3,4)
    deque([1, 2, 3, 4]) --> instead of appendleft() we use append for deque in concat right?
```

**Comment by AbhinavOmprakash** [comment]
yes exactly!
